### ISSUE TITLE
/is visit bug paper1.18.2

### ISSUE THREAD

**Issue by BigAppleClass** [BentoBoxWorld/Visit#15]
### Expected behavior

/is visit is normal

### Observed/Actual behavior

background error

### Steps/models to reproduce

[04:00:08 INFO]: Naive_god issued server command: /is visit
[04:00:16 WARN]: [BentoBox] Task #1900 for BentoBox v1.20.0 generated an exception
java.lang.NullPointerException: Cannot be called on a non-player User!
        at java.util.Objects.requireNonNull(Objects.java:233) ~[?:?]
        at world.bentobox.bentobox.api.user.User.getWorld(User.java:535) ~[[空岛]BentoBox-1.20.0.jar:?]
        at world.bentobox.bentobox.hooks.VaultHook.deposit(VaultHook.java:138) ~[[空岛]BentoBox-1.20.0.jar:?]
        at world.bentobox.visit.managers.VisitAddonManager.depositCredits(VisitAddonManager.java:218) ~[Visit-1.4.0.jar:?]
        at world.bentobox.visit.managers.VisitAddonManager.processTeleportation(VisitAddonManager.java:333) ~[Visit-1.4.0.jar:?]
        at world.bentobox.visit.commands.player.VisitPlayerCommand.lambda$execute$3(VisitPlayerCommand.java:213) ~[Visit-1.4.0.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.18.2.jar:git-Paper-234]
        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.18.2.jar:git-Paper-234]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1535) ~[paper-1.18.2.jar:git-Paper-234]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:483) ~[paper-1.18.2.jar:git-Paper-234]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1458) ~[paper-1.18.2.jar:git-Paper-234]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1227) ~[paper-1.18.2.jar:git-Paper-234]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.2.jar:git-Paper-234]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[04:00:38 INFO]: Naive_god issued server command: /is visit
[04:00:41 WARN]: [BentoBox] Task #1926 for BentoBox v1.20.0 generated an exception
java.lang.NullPointerException: Cannot be called on a non-player User!
        at java.util.Objects.requireNonNull(Objects.java:233) ~[?:?]
        at world.bentobox.bentobox.api.user.User.getWorld(User.java:535) ~[[空岛]BentoBox-1.20.0.jar:?]
        at world.bentobox.bentobox.hooks.VaultHook.deposit(VaultHook.java:138) ~[[空岛]BentoBox-1.20.0.jar:?]
        at world.bentobox.visit.managers.VisitAddonManager.depositCredits(VisitAddonManager.java:218) ~[Visit-1.4.0.jar:?]
        at world.bentobox.visit.managers.VisitAddonManager.processTeleportation(VisitAddonManager.java:333) ~[Visit-1.4.0.jar:?]
        at world.bentobox.visit.commands.player.VisitPlayerCommand.lambda$execute$3(VisitPlayerCommand.java:213) ~[Visit-1.4.0.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.18.2.jar:git-Paper-234]
        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.18.2.jar:git-Paper-234]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1535) ~[paper-1.18.2.jar:git-Paper-234]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:483) ~[paper-1.18.2.jar:git-Paper-234]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1458) ~[paper-1.18.2.jar:git-Paper-234]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1227) ~[paper-1.18.2.jar:git-Paper-234]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.2.jar:git-Paper-234]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
> 

### BentoBox version

[04:03:54 INFO]: 服务器： PAPER 无效
[04:03:54 INFO]: BentoBox 版本： 1.20.0
[04:03:54 INFO]: 数据库： JSON
[04:03:54 INFO]: 已载入的游戏世界：
[04:03:54 INFO]: bskyblock_world (BSkyBlock) : 主世界, 下界, 末地
[04:03:54 INFO]: 已载入的附加组件：
[04:03:54 INFO]: Biomes 2.0.0 (ENABLED)
[04:03:54 INFO]: BSkyBlock 1.15.2 (ENABLED)
[04:03:54 INFO]: Challenges 0.8.4 (ENABLED)
[04:03:54 INFO]: Level 2.9.0 (ENABLED)
[04:03:54 INFO]: Visit 1.4.0 (ENABLED)
[04:03:54 INFO]: Warps 1.11.2 (ENABLED)

### Plugin list

no

### Other

no

**Comment by BONNe** [comment]
Could you test it with Visit 1.5.0-dev?

You can get it at https://ci.codemc.io/job/BentoBoxWorld/job/Visit/

By the error message, it looks like the player tries to visit the island without an owner. I think I fixed it in the latest dev version.

**Comment by BigAppleClass** [comment]
Thank you very much, the beta version is running stably. And the support for Chinese is very good

[04:31:22 INFO]: Naive_god issued server command: /is visit
[04:31:30 INFO]: [BentoBox] [Visit] Naive_god called: `island visit 51655ae6-e4b1-3cf3-b15e-c6c8a5b2edc9 bypass`

![image](https://user-images.githubusercontent.com/37060740/157320107-e978e049-d496-49e0-bab8-6be35aa3d970.png)
